name: mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Navigation
  go_router: ^12.1.3
  
  # Networking
  dio: ^5.4.0
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  
  # Error Tracking
  sentry_flutter: ^7.17.0
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  
  # UI/UX & Icons
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  lottie: ^3.0.0
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Standard lints
  custom_lint: ^0.5.7
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.11

flutter:
  uses-material-design: true
  assets:
    - assets/branding/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/branding/app_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#102216"
  image: "assets/branding/app_icon.png"
  background_image: "assets/branding/splash_bg.png"
  android_12:
    color: "#102216"
    image: "assets/branding/app_icon.png"
  fullscreen: true
